Add two options
RoelVB/ChromeKeePass pull request #38
Opened 2021-04-01 18:28 UTC by Abestanis

This adds two new options:

* Allow to hide the footer in the credentials dropdown:
  ![The new option in the settings.](https://user-images.githubusercontent.com/6966049/113337299-e29ed600-9327-11eb-9e90-5b177637c8e5.png)
  I'm personally not a fan of the footer, it doesn't really serve a purpose, so I would like to be able to disable it.
  It is of course still enabled by default. I put it into a `Theme` group, because there will be other options added in future commits.
* Allow to open the credential dropdown when clicking on the input field.
  ![The new option in the settings.](https://user-images.githubusercontent.com/6966049/113337691-6c4ea380-9328-11eb-8c87-39698b1fd6b2.png)
  This makes the extension behave more like the auto-fill builtin Google Chrome. It is not enabled by default, to preserve existing configurations. Do you think it should be enabled by default?

This also changes the behavior of the credentials dropdown when the input filed gets focus: It does no longer show the dropdown if there is no choice to make, i.e if there is only one credential. This woks especially well with the `autoFillSingleCredential` setting enabled. This makes this extension much less intrusive and also more like the auto-fill builtin Google Chrome.

2021-04-03 13:20 UTC, RoelVB requested changes

2021-04-03 13:20 UTC, RoelVB commented on src/classes/FieldSet.ts
> +            this._openDropdown(this._controlField, false);
I don't like this.
The user chooses to show the dropdown on focus, but when there's only a single result you ignore this setting. Why?

2021-04-03 13:20 UTC, RoelVB commented on src/classes/FieldSet.ts
> +            this._openDropdown(this._controlField);
Please don't change the coding style.
No this method is the only one where the curly braces are on the same line as the statement.

2021-04-03 14:38 UTC, RoelVB commented on src/classes/FieldSet.ts
> +            this._openDropdown(this._controlField, false);
I would suggest something like:
`this._openDropdown(this._controlField, !this._pageControl.settings.autoFillSingleCredential);`

2021-04-03 19:17 UTC, Abestanis commented on src/classes/FieldSet.ts
> +            this._openDropdown(this._controlField, false);
Ok, that works for me. I just think that most that most people will find it not intuitive that we treat an input that has focus on page load as _getting_ focused.

Actually, I just remembered that I made it an explicit setting to control this in a later commit. I will try to see if I can include that commit on this branch.

2021-04-03 19:29 UTC, Abestanis commented on src/classes/FieldSet.ts
> +            this._openDropdown(this._controlField, false);
Ok, I managed to cherry pick that commit, so it is now included on this branch. I also updated the pull request description.

2021-04-03 19:43 UTC, Abestanis commented on src/classes/FieldSet.ts
> +            this._openDropdown(this._controlField);
> Now this method is the only one where the curly braces are on the same line as the statement.

Hm, that is no longer true, my last pull request included some:
https://github.com/RoelVB/ChromeKeePass/blob/44c09e9ff60a8fd856a0b3099bd8ce0a99e2c4a2/src/Settings.ts#L47
https://github.com/RoelVB/ChromeKeePass/blob/44c09e9ff60a8fd856a0b3099bd8ce0a99e2c4a2/src/classes/BasicAuth.ts#L115

My apologies, it is not my intention to force a coding style, I just use the one that is configured in my IDE by default.
In my defense, there is no code of conduct that specifies the coding style, so I just assumed you didn't care.

Now I am of course happy to change the formatting style in my IDE, but I already committed a lot of changes with the default style. Of course, I'm happy to reformat for every branch and pull request in the future and add one extra commit with the code style changes at the end, but given the fact that there are already changes on the `dev` branch, could you ignore the code style for now and do one reformat when we are done merging all the changes? That would save me a bit of work. I also fear that it will make it way harder for me to rebase my other changes onto the `dev` branch, when the pull requests get merged.

2021-04-04 09:10 UTC, RoelVB commented on src/classes/FieldSet.ts
> +            this._openDropdown(this._controlField);
I didn't notice them in the previous PR.
It's not that big of a deal, but I don't like the inconsistency.

2021-04-04 09:13 UTC, RoelVB commented on src/classes/FieldSet.ts
> +            this._openDropdown(this._controlField, false);
Looks good.
You made a small mistake with the selector for the inputfield. I corrected it in b425c7e500bd861bd6d18b89499df6917e6e1de2

2021-04-04 09:15 UTC, RoelVB approved these changes

2021-04-04 09:16 UTC, RoelVB commented
Thanks again for your work. I appreciate it.

2021-04-04 09:16 UTC, merged

2021-04-04 09:19 UTC, Abestanis commented on src/options.ts
> -        $('#showDropdownOnPageLoadFocus').prop('checked', settings.showDropdownOnDetectionFocus);
Good catch!