Improve the style of the settings UI
RoelVB/ChromeKeePass pull request #42
Opened 2021-04-06 18:59 UTC by Abestanis

_This pull request includes the commit from #41, because it adds a setting. Review that one before reviewing this._

This pull request changes the style of the settings dialog to look more like the Google Chrome settings, to give the user a more consistent look and feel.

<details>
<summary>Comparison of the settings dialog before and after.</summary>

| Before | After |
| ------- | ------  |
| ![Old Settings - Upper part](https://user-images.githubusercontent.com/6966049/113762258-b2d14300-9718-11eb-9a44-92462c2a5e78.png) ![Old Settings - Lower part](https://user-images.githubusercontent.com/6966049/113762661-1bb8bb00-9719-11eb-90b3-c6907eec3d10.png) | ![New Settings - Upper part](https://user-images.githubusercontent.com/6966049/113762362-cbd9f400-9718-11eb-8aed-5dc4af297191.png) ![New Settings - Lower part](https://user-images.githubusercontent.com/6966049/113762457-e2804b00-9718-11eb-8945-b455afad6d18.png) |
</details>

A `Cancel` button is added which allows to close the dialog without saving any changes. The `x` on the top right does the same thing, but the `Cancel` button is commonly used in dialogues in the Chrome settings.

Additionally, in the shortcuts section a link to the Chromes shortcut manager is added for the users convenience. An unassigned shortcut is now marked as `<Unassigned>` in the list.

2021-04-08 17:28 UTC, RoelVB commented
Looks really nice.
This was on my todo-list 😄

2021-04-13 17:06 UTC, RoelVB requested changes

2021-04-13 17:06 UTC, RoelVB commented on src/options.ts
> +    $('#cancel').on('click', closeOptionDialog);
The cancel button doesn't work on Microsoft Edge (`window.close()` does nothing). I couldn't find an alternative for Edge. The only "solutions" I could think of is:
```suggestion
    if(navigator.userAgent.indexOf('Edg/') !== -1) // Edge doesn't support closing
        $('#cancel').remove();
    else
        $('#cancel').on('click', closeOptionDialog);
```

2021-04-13 17:44 UTC, Abestanis commented on src/options.ts
> +    $('#cancel').on('click', closeOptionDialog);
I was unaware that we support other browsers than Chrome. I just tried it and the settings page does not look very good on Edge. Let me see what I can come up with.

Also, should `You can change shortcuts using the Extensions > Keyboard Shortcuts option in Chrome` be changed into `You can change shortcuts using the Extensions > Keyboard Shortcuts options`?

2021-04-13 17:49 UTC, RoelVB commented on src/options.ts
> +    $('#cancel').on('click', closeOptionDialog);
The readme contains the name "EdgeKeePass" 😉
It already looks better on Edge than before. The problem is that the options dialog in Edge has a fixed width of 400px.

Yes. It would make sense to change this text. Good catch.

2021-04-13 19:49 UTC, Abestanis commented on src/options.ts
> +    $('#cancel').on('click', closeOptionDialog);
I played around for a bit but I couldn't find a better solution. I also took the opportunity to fix the `host` and `port` inputs appearing on two different lines in Edge because of the smaller dialog. I think it looks acceptable now:

<details>
<summary>Screenshot</summary>

![Settings on the Edge browser](https://user-images.githubusercontent.com/6966049/114611972-d872c500-9ca1-11eb-9625-3ef76aef0cb5.png)
</details>

2021-04-14 15:42 UTC, merged

2021-04-14 15:43 UTC, RoelVB commented
Shall I release a new version with all those great changes or do you have more up your sleeve?

2021-04-14 21:35 UTC, Abestanis commented
I got a some more commits, but it is up to you. If you are interested in whats left, you can see the commits [here](https://github.com/Abestanis/ChromeKeePass/commits/feature/improvements).

I will let you know on the last pull request, so we can also do the reformatting.